#pragma once
#include <map>
#include <vector>
#include <string>

std::map<int, std::vector < std::string >> g_ObjectVarNames = {
{7 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{12 , {"callback", "choice", "click_event", "click_sound", "disabled", "hover", "img", "is_active", "open", "override_index", "pressed", "razdel", "razdel_check", "state_images", "toggle", "update_image", "xx"}},
{13 , {"__sprite", "callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "razdel", "state_images", "toggle", "update_image", "xx"}},
{16 , {"active", "area_height", "area_xmax", "area_xmin", "area_ymax", "area_ymin", "drag_origin", "drag_origin_percent", "in_area", "is_scrolling", "joy_step", "make", "make_minmax", "max_scroll", "scroll", "scroll_by", "scroll_into_view", "scroll_mouse", "scroll_percent", "scroll_real", "scroll_real_percent", "scroll_ymax", "scroller", "scroller_pos", "scroller_resize_move", "set_max_scroll", "set_scroll", "set_smooth_scroll", "wheel_step"}},
{18 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{20 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1"}},
{23 , {"check_overflow", "count", "destroy", "ex_delay", "index", "init", "move_dir", "p_frame", "potential", "redraw", "relocate", "relocating", "res_surf", "sh_col1", "sh_col2", "sh_t", "slot", "snd", "spawn", "text", "text_chunk", "text_full", "tweener", "type"}},
{24 , {"callback", "choice", "click_event", "click_sound", "col", "disabled", "hover", "is_active", "open", "override_index", "pressed", "razdel", "razdel_check", "state_images", "toggle", "update_image", "xx"}},
{37 , {"active", "active_check", "clicked", "hover", "pressed", "razdel", "razdel_check", "steps", "text", "trueval", "val", "width", "xx"}},
{45 , {"active_check", "anim", "callback", "choice", "click_event", "click_sound", "col", "disabled", "hero_img", "hover", "is_active", "open", "override_index", "pressed", "razdel", "razdel_check", "state_images", "toggle", "update_image", "xx"}},
{57 , {"active", "active_check", "clicked", "hover", "pressed", "razdel", "razdel_check", "steps", "text", "trueval", "val", "width", "xx"}},
{59 , {"active", "num", "num_check", "xorig", "xshift"}},
{60 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "lang_init", "language", "number", "override_index", "pressed", "state_images", "text_lang", "toggle", "update_image", "xx"}},
{66 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{68 , {"BEGIN_HTTP_UPLOAD_WAIT_SECONDS", "auth_steam_account", "batch_e_result", "cancel", "check_data_format", "client_id", "cloud_save_state", "complete_batch", "complete_batch_attempts", "download_steam_file", "file_downloading", "file_get_request", "file_get_retry_count", "file_sha", "get_cloud_files", "get_files_request_id", "get_id_request_id", "get_state_string", "get_steam_id", "http_request_id", "init_switch_saves", "load_meta_data", "login_switch_user", "max_complete_batch_attempts", "max_retries", "meta_data_file_path", "meta_data_map", "number_of_files", "parse_enumerate_result_data", "parse_get_id_result_data", "pc_steam_load", "process_http_result", "reauthorize", "redirect_uri", "save_meta_data", "status_map", "steam_access_token", "steam_api", "steam_app_id", "steam_begin_http_upload", "steam_cloud_post_request", "steam_cloud_put_request", "steam_commit_http_upload", "switch_network_function", "switch_show_error", "switch_user_account_id", "switch_user_logged_in", "temp_file", "testing_token_set", "upload_next_file", "upload_steam_file", "upload_steam_files_batch"}},
{69 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{74 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{84 , {"active", "active_check", "checked", "hover", "init", "nohover", "pressed", "razdel", "scale", "xx"}},
{88 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{94 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{99 , {"callback", "click_event", "click_sound", "deck", "disabled", "hover", "is_active", "override_index", "perks", "pressed", "state_images", "toggle", "update_image"}},
{103 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yy"}},
{105 , {"_fps", "_opt_x", "_slide_chan", "_slide_x", "ach_height", "ach_scroll", "achiv_move", "achiv_redraw", "achiv_show", "achiv_surf", "font_but_w", "font_opt_surf", "font_opt_surfscale", "font_redraw", "info_left", "info_timer", "menu_redraw", "mouse_vol", "move", "music_select", "opt_menu_razdel", "opt_menu_surf", "opt_menu_surf_vid", "opt_move", "opt_open", "opt_top_h", "opt_video_h", "opt_windows_move", "sachiv_show", "save_draw", "scroller", "scrsh", "scrsh_max", "sh_EXTREME", "sh_blursize", "sh_intensity", "sh_scale", "sh_sizes", "slide_move", "spd"}},
{107 , {"amount0", "amount1", "amount2", "amount3", "animate_expedition", "ay", "camp_frame", "camp_river_img", "closeMenus", "img_speed", "myy", "res0", "res1", "res2", "res3", "shift_last", "show_camp_buttons", "surf_txt"}},
{108 , {"alpha", "alpha_speed", "alpha_text", "click", "intro_number", "intro_skip", "s_logo", "s_logo2", "skip", "text"}},
{114 , {"callback", "click_event", "click_sound", "disabled", "fa_cnt", "fa_cntv", "fa_cntv1", "fa_cntv2", "fa_ltxt", "fa_width", "hover", "is_active", "max_width", "override_index", "press_text", "pressed", "state_images", "sy", "text", "text1", "text2", "text_align", "text_colors", "text_index", "text_key", "text_padding", "text_type", "text_x", "text_y", "toggle", "tutor_kill", "type", "update_image"}},
{118 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "state_images", "sy", "toggle", "update_image"}},
{119 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "state_images", "sy", "toggle", "update_image"}},
{125 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "state_images", "toggle", "update_image"}},
{131 , {"btnsnd", "can_move", "close", "close_btn", "drw_card_list", "fa_cnt", "move", "move_real", "move_step", "my", "submenu", "text", "text_statlist", "tutorial_mode"}},
{132 , {"callback", "click_event", "click_sound", "disabled", "fa_cnt", "fa_cntv", "fa_ltxt", "fa_width", "hover", "is_active", "max_width", "override_index", "press_text", "pressed", "state_images", "text", "text_align", "text_colors", "text_index", "text_key", "text_padding", "text_type", "text_x", "text_y", "toggle", "update_image"}},
{133 , {"num", "type"}},
{134 , {"backind", "callback", "card_index", "card_max", "card_min", "card_type", "cards_dup", "cards_nonexistent", "cards_type", "click_event", "click_sound", "deck_change", "deck_change_img", "deck_change_spd", "deck_sum", "deck_valid", "disabled", "enabled", "hover", "is_active", "override_index", "pressed", "state_images", "toggle", "type_card_max", "type_card_min", "type_card_take", "update_image"}},
{136 , {"activate", "appear", "backind", "card_become_old", "card_double", "card_index", "card_new", "card_new_img", "card_new_spd", "card_type", "cardsurf", "click", "destroy", "double_shift", "doublesurf", "locked", "name", "name_dub", "num", "redraw", "sh_col1", "sh_col2", "sh_t", "sh_t_spd", "sound", "text", "vibe", "xx", "yy"}},
{137 , {"button_surf", "close_btn", "my", "redraw", "scroller", "text", "text_surf"}},
{138 , {"LL", "LLL", "LLM", "LU", "LUM", "LUU", "RR", "RRM", "RRRR", "RRU", "RU", "RUM", "RUU", "RUUULLLUL", "UL", "UR", "UU", "amount0", "amount1", "amount2", "amount3", "btn", "build_can", "build_max", "build_num", "click", "image_ind", "index", "name", "ramka_img", "res0", "res1", "res2", "res3", "yy"}},
{140 , {"close_btn", "my", "redraw", "scroller", "stat_width", "statsurf", "text"}},
{176 , {"build", "forest", "image", "image_ind", "image_num", "image_spd", "tile_bridge", "tile_canupgrade", "tile_index", "tile_level", "tile_number", "tile_river", "upgrade_timer", "zero_type"}},
{178 , {"button_draw", "fa_cnt", "fa_cntv", "selected", "selected_menu", "text"}},
{179 , {"button_draw", "fa_cnt", "fa_cntv", "selected", "selected_menu", "text"}},
{180 , {"button_draw", "fa_cnt", "fa_cntv", "selected", "selected_menu", "text"}},
{188 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "state_images", "toggle", "update_image"}},
{193 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{226 , {"active", "active_check", "checked", "h", "hover", "nohover", "pressed", "razdel", "razdel_check", "state", "type", "w", "x1", "xx", "y1", "yorig", "yy"}},
{279 , {"gamepad_dist", "gamepad_visibility", "mouse_x_prev", "mouse_y_prev"}},
{292 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "pressed", "state_images", "toggle", "update_image"}},
{295 , {"callback", "click_event", "click_sound", "disabled", "hover", "is_active", "override_index", "owner", "pressed", "state_images", "toggle", "update_image"}},
{298 , {"backind", "blink_speed", "blink_t", "card_index", "card_max", "card_min", "card_type", "cards_dup", "cards_nonexistent", "cards_type", "deck_sum", "deck_valid", "type_card_max", "type_card_min", "type_card_take"}},
};
